bower.json
=> Updates app-selector to v1.0.11

src/elements/common-elements/engagement-overview-components/engagement-staff-members-tab/engagement-staff-members-tab.spec.html, src/elements/data-elements/get-staff-members-list.html
=> adds current user country name query param to audit staff members

bower.json, package-lock.json, package.json, src/elements/app-behaviors/query-params-controller.html, src/elements/common-elements/search-and-filter-element/search-and-filter.html, src/elements/common-elements/search-and-filter-element/search-and-filter.js, src/elements/common-elements/search-and-filter-element/search-and-filter.scss, src/elements/common-elements/search-and-filter-element/search-and-filter.spec.html, src/elements/data-elements/engagements-list-data.html, src/elements/pages/engagements-page-components/engagements-list-view/engagements-list-view.js, src/elements/pages/engagements-page-components/engagements-list-view/engagements-list-view.spec.html, src/elements/pages/staff-sc-page-components/staff-sc-page-main/staff-sc-page-main.js
[ch7916]
@v-urbanovich this is a change to make the filters multi-select and to have the same UI behavior as other modules like Dashboard and PMP.
=> Change filters UI, adds multi select

src/elements/app-behaviors/query-params-controller.html, src/elements/data-elements/engagements-list-data.html, src/elements/pages/engagements-page-components/engagements-list-view/engagements-list-view.html, src/elements/pages/engagements-page-components/engagements-list-view/engagements-list-view.js
=> adds filtering params to export

src/elements/pages/spot-checks-page-components/spot-checks-page-main/spot-checks-page-main.html, src/elements/pages/spot-checks-page-components/spot-checks-page-main/spot-checks-page-main.js
swapped etools-dialog on spot-checks-page-main
=> added etools-dialog to spot-checks-cancelation

src/elements/pages/audits-page-components/report-page-components/financial-findings/financial-findings.html, src/elements/pages/audits-page-components/report-page-components/financial-findings/financial-findings.js
added etools-dialog to financial-findings
=> added etools-dialog to financial-findings

src/elements/app-behaviors/table-elements-behavior.html, src/elements/common-elements/file-attachments-tab/file-attachments-tab.js, src/elements/pages/spot-checks-page-components/report-page-components/summary-findings-element/summary-findings-element.html, src/elements/pages/spot-checks-page-components/report-page-components/summary-findings-element/summary-findings-element.js
replaced dialog-element on summary-findings-element
=> Replace dialog summary findings

src/elements/pages/audits-page-components/report-page-components/findings-summary/findings-summary.html, src/elements/pages/audits-page-components/report-page-components/findings-summary/findings-summary.js
added etools-dialog to findings-summary
=> added etools-dialog to findings-summary

bower.json, src/elements/app-behaviors/engagement-behavior.html, src/elements/common-elements/engagement-overview-components/engagement-staff-members-tab/engagement-staff-members-tab.js, src/elements/common-elements/follow-up-components/follow-up-actions/follow-up-actions.js, src/elements/data-elements/check-user-existence.html, src/elements/data-elements/engagements-list-data.html, src/elements/data-elements/get-action-points.html, src/elements/data-elements/get-agreement-data.html, src/elements/data-elements/get-attachments.html, src/elements/data-elements/get-partner-data.html, src/elements/data-elements/update-action-points.html, src/elements/data-elements/update-agreement-data.html, src/elements/data-elements/update-attachments.html, src/elements/data-elements/user-data.html, src/elements/pages/staff-sc-page-components/staff-sc-page-main/staff-sc-page-main.html, src/elements/pages/staff-sc-page-components/staff-sc-page-main/staff-sc-page-main.js
=> Update etools-ajax code

src/elements/core-elements/app-sidebar-menu/app-sidebar-menu.html
=> Updates info link on sidebar

bower.json
=> Updates etools-app-selector to v1.1.8

src/elements/core-elements/app-main-header/app-main-header/app-main-header.html
=> Changes logout link to /logout

src/elements/pages/engagements-page-components/engagements-list-view/engagements-list-view.js
=> Fixes Joint Audit filter

package-lock.json, src/elements/app-behaviors/engagement-behavior.html, src/elements/app-behaviors/table-elements-behavior.html, src/elements/common-elements/file-attachments-tab/file-attachments-tab.html, src/elements/common-elements/file-attachments-tab/file-attachments-tab.js, src/elements/common-elements/file-attachments-tab/file-attachments-tab.scss, src/elements/common-elements/list-tab-elements/list-element/list-element.scss, src/elements/common-elements/list-tab-elements/list-header/list-header.scss, src/elements/common-elements/search-and-filter-element/search-and-filter.js, src/elements/common-elements/share-documents/share-documents.html, src/elements/common-elements/share-documents/share-documents.js, src/elements/common-elements/share-documents/share-documents.scss, src/elements/common-elements/simple-list-item/simple-list-item.html, src/elements/common-elements/simple-list-item/simple-list-item.scss, src/elements/core-elements/app-config/etools-app-config.html, src/elements/data-elements/engagement-info-data.html, src/elements/data-elements/static-data.html, src/elements/data-elements/update-attachments.html, src/elements/data-elements/update-engagement.html, src/elements/pages/engagements-page-components/new-engagement-view/new-engagement-view-main/new-engagement-view.spec.html, src/elements/pages/spot-checks-page-components/spot-checks-page-main/spot-checks-page-main.html, src/elements/styles-elements/app-theme.html, src/elements/styles-elements/etools-file-styles.html, src/elements/styles-elements/module-styles.html, src/elements/styles-elements/tab-inputs-styles.html
=> FAM Sharing of Documents

src/elements/common-elements/file-attachments-tab/file-attachments-tab.html, src/elements/common-elements/file-attachments-tab/file-attachments-tab.js, src/elements/pages/audits-page-components/audits-page-main/audits-page-main.html, src/elements/pages/micro-assessments-page-components/micro-assessments-page-main/micro-assessments-page-main.html, src/elements/pages/special-audits-page-components/special-audits-page-main/special-audits-page-main.html, src/elements/pages/spot-checks-page-components/spot-checks-page-main/spot-checks-page-main.html
=> omits link attachments from report tab

src/elements/common-elements/share-documents/share-documents.js, src/elements/pages/audits-page-components/report-page-components/findings-summary/findings-summary.js, src/elements/pages/audits-page-components/report-page-components/findings-summary/findings-summary.spec.html
=> remove defaulting 0s

src/elements/pages/engagements-page-components/engagements-list-view/engagements-list-view.js
=> renamed auditor fim to audit firm

src/elements/common-elements/share-documents/share-documents.html, src/elements/common-elements/share-documents/share-documents.scss
adds a message when share docs list is empty
=> Hide share auditors

src/elements/pages/engagements-page-components/engagements-list-view/engagements-list-view.js, src/elements/pages/staff-sc-page-components/staff-sc-page-main/staff-sc-page-main.js
=> Fixed missing filter labels

src/elements/core-elements/app-config/etools-app-config.html, src/elements/core-elements/app-main-header/app-main-header/app-main-header.html
=> Adds env warnings for remaining environments

src/elements/data-elements/get-staff-members-list.html
=> change url for staff spot check user lookup

src/elements/common-elements/engagement-overview-components/engagement-staff-members-tab/engagement-staff-members-tab.js, src/elements/core-elements/app-config/etools-app-config.html, src/elements/data-elements/check-user-existence.html, src/elements/pages/staff-sc-page-components/staff-sc-page-main/staff-sc-page-main.js
=> fix error when adding new member

src/elements/core-elements/app-main-header/app-main-header/app-main-header.html, src/elements/core-elements/app-main-header/app-main-header/support-btn.html, src/elements/styles-elements/app-theme.html, src/index.html
=> [PROD] Support button

src/elements/common-elements/dialog-element/dialog-element.html, src/elements/data-elements/check-user-existence.html
=> better error messages, fixes disabling of add button on errors

src/elements/app-behaviors/engagement-behavior.html, src/elements/app-behaviors/tests/engagement-behavior.spec.html
=> allow focal points to view report tab

src/elements/pages/audits-page-components/report-page-components/financial-findings/financial-findings.js
=> sort findings options alphabetically

bower.json, src/elements/core-elements/app-shell-element/app-shell.html, src/elements/core-elements/app-shell-element/app-shell.spec.html
=> Adds etools-piwik-analytics

src/elements/app-behaviors/engagement-behavior.html, src/elements/common-elements/file-attachments-tab/file-attachments-tab.js, src/elements/pages/micro-assessments-page-components/micro-assessments-page-main/micro-assessments-page-main.html, src/elements/pages/micro-assessments-page-components/report-page-components/report-page-main/ma-report-page-main.html
=> hides report fields that have no values, fixes questionnaire showing

src/elements/pages/audits-page-components/audits-page-main/audits-page-main.html, src/elements/pages/micro-assessments-page-components/micro-assessments-page-main/micro-assessments-page-main.html, src/elements/pages/special-audits-page-components/special-audits-page-main/special-audits-page-main.html, src/elements/pages/spot-checks-page-components/spot-checks-page-main/spot-checks-page-main.html
=> hides report attachments on newly created engagement

src/elements/common-elements/file-attachments-tab/file-attachments-tab.html, src/elements/common-elements/file-attachments-tab/file-attachments-tab.js
=> Hide extra blank row

src/elements/core-elements/app-config/etools-app-config.html
=> Updates users endpoint

src/elements/common-elements/file-attachments-tab/file-attachments-tab.html, src/elements/common-elements/file-attachments-tab/file-attachments-tab.js, src/elements/pages/engagements-page-components/new-engagement-view/new-engagement-view-main/new-engagement-view.html, src/elements/pages/engagements-page-components/new-engagement-view/new-engagement-view-main/new-engagement-view.js, src/elements/styles-elements/app-theme.html, src/elements/styles-elements/shared-styles.html
=> Fix create engagement with more than 1 attachment

src/elements/styles-elements/app-theme.html, src/index.html
=> [ch11973]Web-components v0 deprecation related

src/elements/app-behaviors/common-methods-behavior.html, src/elements/app-behaviors/engagement-behavior.html, src/elements/app-behaviors/table-elements-behavior.html, src/elements/common-elements/engagement-overview-components/engagement-info-details/engagement-info-details.js, src/elements/common-elements/file-attachments-tab/file-attachments-tab.js, src/elements/common-elements/multi-notifications/multi-notification-item.js, src/elements/common-elements/share-documents/share-documents.js, src/elements/pages/micro-assessments-page-components/questionnaire-components/risk-tab/risk-tab.js
=> [ch12733]Shaddy dom related fixes

src/elements/common-elements/file-attachments-tab/file-attachments-tab.js
=> Remove finally

src/elements/core-elements/app-config/etools-app-config.html, src/elements/data-elements/get-attachments.html
=> Force Get all on paginated endpoint

src/elements/pages/micro-assessments-page-components/questionnaire-components/risk-tab/risk-tab.js, src/elements/pages/micro-assessments-page-components/questionnaire-components/risk-tab/risk-tab.spec.html
=> Fix dialog not opening in last panel from questionnaire tab

src_ts/elements/common-elements/file-attachments-tab/file-attachments-tab-styles.ts, src_ts/elements/common-elements/file-attachments-tab/file-attachments-tab.ts, src_ts/elements/pages/audits-page-components/audits-page-main/audits-page-main.ts, src_ts/elements/pages/engagements-page-components/new-engagement-view/new-engagement-view.ts
=> Audits main page elem polymer 3 migration

src_ts/elements/common-elements/list-tab-elements/list-pagination/list-pagination.ts, src_ts/elements/core-elements/app-shell-element/app-shell.ts, src_ts/elements/core-elements/app-sidebar-menu/app-menu.ts, src_ts/elements/core-elements/app-sidebar-menu/mixins/app-menu-mixin.ts, src_ts/elements/core-elements/app-sidebar-menu/styles/app-drawer-styles.ts, src_ts/elements/core-elements/app-sidebar-menu/styles/nav-menu-styles.ts
fixed pagination styles
fixed side nav styles
=> Fix style issues

src_ts/elements/data-elements/user-data.ts
=> fix user data

package.json, src_ts/elements/styles-elements/app-theme.ts
[ch12902] FAM migration - user-profile-dialog, etools-profile-dropdown issues
=> [ch12902] FAM migration - user-profile-dialog, etools-profile-dropdown issues

src_ts/elements/pages/audits-page-components/report-page-components/assessment-of-controls/assessment-of-controls.ts, src_ts/elements/pages/audits-page-components/report-page-components/audit-report-page-main/audit-report-page-main.ts, src_ts/elements/pages/audits-page-components/report-page-components/key-internal-controls-weaknesses/key-internal-controls-weaknesses.ts, src_ts/elements/pages/audits-page-components/report-page-components/kicw-risk/kicw-risk.ts
Poly3 migration: report-page-components
=> Poly3 migration: report-page-components

src_ts/elements/common-elements/search-and-filter-element/search-and-filter.ts
Migration to Poly3 filtering fix
=> Migration to Poly3 filtering fix

src_ts/elements/common-elements/share-documents/share-documents.ts, src_ts/elements/common-elements/simple-list-item/simple-list-item.ts
Migration Poly3 fix attachment style
=> Migration Poly3 fix attachment style

src_ts/elements/common-elements/search-and-filter-element/search-and-filter.ts
=> Migration Poly3 Filtering fix

src_ts/elements/common-elements/engagement-overview-components/engagement-info-details/engagement-info-details.ts, src_ts/elements/common-elements/engagement-overview-components/partner-details-tab/partner-details-tab.ts, src_ts/elements/pages/audits-page-components/report-page-components/key-internal-controls-weaknesses/key-internal-controls-weaknesses.ts
=> Migration audits fixes

bower.json, src/elements/core-elements/app-main-header/app-main-header/app-main-header.html, src/elements/core-elements/app-shell-element/app-shell.js, src/elements/data-elements/check-user-existence.html
=> Updates etools-app-selector to v1.1.10, fixes user structure

src_ts/elements/styles-elements/tab-inputs-styles.ts
=> Poly3 datepicker fix

src_ts/elements/common-elements/engagement-overview-components/engagement-staff-members-tab/engagement-staff-members-tab.ts, src_ts/elements/common-elements/list-tab-elements/list-pagination/list-pagination.ts, src_ts/elements/styles-elements/tab-inputs-styles.ts
DatePicker layout fixes
Table pagination was missing
Table pagination layout fix
Table Header search fix
=> Migration fixes 1

src_ts/elements/common-elements/engagement-report-components/assign-engagement/assign-engagement.ts, src_ts/elements/common-elements/file-attachments-tab/file-attachments-tab.ts, src_ts/elements/styles-elements/tab-inputs-styles.ts
Required icon layout fix
Fixed console error on opening app
Fixed assign-engagement error
=> Migration Poly 3 fixes

src_ts/elements/common-elements/engagement-overview-components/engagement-staff-members-tab/engagement-staff-members-tab.ts, src_ts/elements/common-elements/pages-header-element/pages-header-element-styles.ts
=> page header style fix

src_ts/elements/common-elements/share-documents/share-documents.ts, src_ts/elements/styles-elements/tab-inputs-styles.ts
Share dialog layout
Datepicker color
=> Migration Poly 3

src_ts/elements/app-mixins/engagement-mixin.ts, src_ts/elements/app-mixins/table-elements-mixin.ts, src_ts/elements/common-elements/engagement-overview-components/engagement-info-details/engagement-info-details.ts, src_ts/elements/common-elements/engagement-overview-components/engagement-staff-members-tab/engagement-staff-members-tab.ts, src_ts/elements/common-elements/file-attachments-tab/file-attachments-tab.ts, src_ts/elements/pages/audits-page-components/report-page-components/financial-findings/financial-findings.ts, src_ts/elements/pages/audits-page-components/report-page-components/key-internal-controls-weaknesses/key-internal-controls-weaknesses.ts, src_ts/elements/pages/spot-checks-page-components/report-page-components/overview-element/overview-element.ts
Dialog Fixes
Various other bug fixes
=> Dialog fixes

src_ts/elements/app-mixins/table-elements-mixin.ts, src_ts/elements/common-elements/follow-up-components/follow-up-actions/follow-up-actions.ts, src_ts/elements/common-elements/follow-up-components/follow-up-main/follow-up-main.ts, src_ts/elements/pages/micro-assessments-page-components/micro-assessments-page-main/micro-assessments-page-main.ts, src_ts/elements/pages/micro-assessments-page-components/questionnaire-components/questionnaire-page-main/questionnaire-page-main.ts, src_ts/elements/pages/micro-assessments-page-components/questionnaire-components/risk-tab/risk-tab.ts, src_ts/elements/pages/spot-checks-page-components/spot-checks-page-main/spot-checks-page-main.ts
Migration Poly3 Questionnaire and Follow-up fixes
=> Migration Poly3 Questionnaire and Follow-up fixes

src_ts/elements/pages/audits-page-components/report-page-components/findings-summary/fundings-summary.ts, src_ts/elements/pages/audits-page-components/report-page-components/key-internal-controls-weaknesses/key-internal-controls-weaknesses.ts, src_ts/elements/pages/audits-page-components/report-page-components/kicw-risk/kicw-risk.ts, src_ts/elements/pages/micro-assessments-page-components/report-page-components/primary-risk-element.ts
Reports fixes (Audit Findings, Key Internal Controls, Key Internal Control Weaknesses)
=> Migration Poly3 fixes

src_ts/elements/app-config/config.ts, src_ts/elements/app-mixins/query-params-controller.ts, src_ts/elements/core-elements/app-main-header/countries-dropdown/countries-dropdown.ts, src_ts/elements/core-elements/app-shell-element/app-shell.ts, src_ts/elements/pages/engagements-page-components/new-engagement-view/new-engagement-view.ts
Refactor AP_DOMAIN to BASE_PATH
=> Refactor AP_DOMAIN to BASE_PATH

src_ts/elements/core-elements/app-main-header/page-header.ts, src_ts/elements/core-elements/app-shell-element/app-shell.ts
Increase responsive width to 1200px
=> Increase responsive width to 1200px

src_ts/elements/pages/engagements-page-components/engagements-page-main/engagements-page-main.ts, src_ts/elements/pages/staff-sc-page-components/staff-sc-page-main/staff-sc-page-main.ts
=> Fix list pagination issue

src_ts/elements/common-elements/engagement-overview-components/engagement-info-details/engagement-info-details.ts, src_ts/elements/common-elements/engagement-report-components/assign-engagement/assign-engagement.ts, src_ts/elements/common-elements/engagement-report-components/specific-procedure/specific-procedure.ts, src_ts/elements/common-elements/share-documents/share-documents.ts, src_ts/elements/pages/audits-page-components/report-page-components/assessment-of-controls/assessment-of-controls.ts, src_ts/elements/pages/audits-page-components/report-page-components/audit-report-page-main/audit-report-page-main.ts, src_ts/elements/pages/audits-page-components/report-page-components/financial-findings/financial-findings.ts, src_ts/elements/pages/audits-page-components/report-page-components/findings-summary/fundings-summary.ts, src_ts/elements/pages/audits-page-components/report-page-components/key-internal-controls-weaknesses/key-internal-controls-weaknesses.ts, src_ts/elements/pages/micro-assessments-page-components/questionnaire-components/questionnaire-page-main/questionnaire-page-main.ts, src_ts/elements/pages/micro-assessments-page-components/report-page-components/primary-risk-element.ts, src_ts/elements/pages/special-audits-page-components/report-page-components/other-recommendations/other-recommendations.ts, src_ts/elements/pages/special-audits-page-components/report-page-components/sa-report-page-main/sa-report-page-main.ts, src_ts/elements/pages/spot-checks-page-components/report-page-components/internal-controls/internal-controls.ts
Fixed Risk Assessment saving
Fixed bug on loading Audit staff members
Fixed TSLint errors
=> Fixed bugs, tsLint errors

src_ts/elements/common-elements/engagement-overview-components/engagement-info-details/engagement-info-details.ts, src_ts/elements/common-elements/engagement-overview-components/partner-details-tab/partner-details-tab.ts, src_ts/elements/common-elements/file-attachments-tab/file-attachments-tab.ts, src_ts/elements/pages/engagements-page-components/new-engagement-view/new-engagement-view.ts
=> New engagement page fix

src_ts/elements/app-mixins/table-elements-mixin.ts, src_ts/elements/data-elements/get-staff-members-list.ts, src_ts/elements/pages/spot-checks-page-components/report-page-components/overview-element/overview-element.ts, src_ts/elements/styles-elements/tab-inputs-styles.ts
Refactored _setRequired method(removed from TableMixin)
=> [ch14098] Required fields issue

src_ts/elements/app-mixins/engagement-mixin.ts, src_ts/elements/common-elements/engagement-overview-components/engagement-staff-members-tab/engagement-staff-members-tab.ts, src_ts/elements/common-elements/file-attachments-tab/file-attachments-tab.ts, src_ts/elements/common-elements/insert-html/insert-html.ts, src_ts/elements/common-elements/list-tab-elements/list-element/list-element.ts, src_ts/elements/common-elements/pages-header-element/pages-header-element.ts, src_ts/elements/common-elements/search-and-filter-element/search-and-filter.ts, src_ts/elements/core-elements/app-footer/page-footer.ts, src_ts/elements/core-elements/app-main-header/countries-dropdown/header-styles.ts, src_ts/elements/core-elements/app-shell-element/app-shell.ts, src_ts/elements/data-elements/static-data.ts, src_ts/elements/pages/audits-page-components/audits-page-main/audits-page-main.ts, src_ts/elements/pages/audits-page-components/report-page-components/audit-report-page-main/audit-report-page-main.ts, src_ts/elements/pages/engagements-page-components/engagements-page-main/engagements-page-main.ts, src_ts/elements/pages/engagements-page-components/new-engagement-view/new-engagement-view.ts, src_ts/elements/styles-elements/tab-inputs-styles.ts
=> Poly3 Migration fixes

src_ts/elements/core-elements/app-main-header/page-header.ts
=> Fixed sign out

src_ts/elements/app-mixins/engagement-mixin.ts
[ch14168] FAM: Unable to cancel an engagement
=> [ch14168] FAM: Unable to cancel an engagement

src_ts/elements/pages/micro-assessments-page-components/questionnaire-components/questionnaire-page-main/questionnaire-page-main.ts, src_ts/elements/pages/micro-assessments-page-components/questionnaire-components/risk-tab/risk-tab.ts
=> [ch14268]Fix edit risk rating

package-lock.json, package.json, src_ts/elements/pages/micro-assessments-page-components/questionnaire-components/questionnaire-page-main/questionnaire-page-main.ts, src_ts/elements/pages/micro-assessments-page-components/questionnaire-components/risk-tab/risk-tab.ts
=> [ch14264] Fix dropdown issues for None, N/A options

src_ts/elements/common-elements/follow-up-components/follow-up-actions/follow-up-actions.ts
[ch14359] Add Action Points from UNICEF Follow-Up Actions Missing
=> [ch14359] Add Action Points from UNICEF Follow-Up Actions Missing

src_ts/elements/common-elements/pages-header-element/pages-header-element.ts
[ch14354] Export to CSV file not working
=> [ch14354] Export to CSV file not working

src_ts/elements/app-mixins/engagement-mixin.ts, src_ts/elements/common-elements/engagement-overview-components/engagement-info-details/engagement-info-details.ts, src_ts/elements/data-elements/update-engagement.ts
=> [ch14630]Fix save staff-spot-check

src_ts/elements/common-elements/follow-up-components/follow-up-financial-findings/follow-up-financial-findings.ts, src_ts/elements/common-elements/follow-up-components/follow-up-main/follow-up-main.ts
[ch14568] Financial Findings Section included in Follow Up Tab for Micro Assessment and Special Audit
=> [ch14568] Financial Findings Section included in Follow Up Tab for Micro Assessment and Special Audit

src_ts/elements/common-elements/file-attachments-tab/file-attachments-tab.ts, src_ts/elements/pages/micro-assessments-page-components/questionnaire-components/questionnaire-page-main/questionnaire-page-main.ts, src_ts/elements/pages/micro-assessments-page-components/questionnaire-components/risk-tab/risk-tab.ts, src_ts/elements/pages/micro-assessments-page-components/report-page-components/control-findings-tab.ts, src_ts/elements/pages/micro-assessments-page-components/report-page-components/key-internal-controls-tab.ts, src_ts/elements/pages/micro-assessments-page-components/report-page-components/primary-risk-element.ts
[ch14345] Report, Questionnaire and Attachments still active after submitting the Report
=> [ch14345] Report, Questionnaire and Attachments still active after submitting the Report

src_ts/elements/app-mixins/table-elements-mixin.ts, src_ts/elements/pages/audits-page-components/report-page-components/assessment-of-controls/assessment-of-controls.ts, src_ts/elements/pages/audits-page-components/report-page-components/audit-report-page-main/audit-report-page-main.ts, src_ts/elements/pages/audits-page-components/report-page-components/findings-summary/fundings-summary.ts, src_ts/elements/pages/micro-assessments-page-components/questionnaire-components/risk-tab/risk-tab.ts, src_ts/elements/pages/micro-assessments-page-components/report-page-components/primary-risk-element.ts
=> [ch14705]Fix 400(Bad request) on select risk rating

package-lock.json, package.json
=> Updates app selector to v3.0.2

src_ts/elements/common-elements/follow-up-components/follow-up-main/follow-up-main.ts
[ch13361] Display the card "Summary of High Priority Findings and Recommendations" in the Follow-up Tab
=> [ch13361] Display the card "Summary of High Priority Findings and Recommendations" in the Follow-up 

src_ts/elements/common-elements/pages-header-element/pages-header-element.ts, src_ts/elements/pages/micro-assessments-page-components/report-page-components/primary-risk-element.ts
=> [ch14900]Fix built code error

src_ts/elements/common-elements/engagement-overview-components/engagement-staff-members-tab/engagement-staff-members-tab.ts
[14709] FAM- validation message cut off
=> [14709] FAM- validation message cut off

package-lock.json, package.json, src_ts/elements/core-elements/app-shell-element/app-shell.ts
=> app selector admin navigation fixes

src_ts/elements/styles-elements/module-styles.ts
[ch15218] FAM-Follow up Action are not aligned
=> [ch15218] FAM-Follow up Action are not aligned

package-lock.json, package.json
=> 15256 upgrade app selector

src_ts/elements/core-elements/app-shell-element/app-shell.ts
[ch15396] On List page of FAM cannot move from one page to another.
=> [ch15396] On List page of FAM cannot move from one page to another.

src_ts/elements/app-mixins/table-elements-mixin.ts, src_ts/elements/common-elements/engagement-overview-components/engagement-staff-members-tab/engagement-staff-members-tab.ts
[ch14709] Prevent adding Audit Staff Team member if email is not valid
=> [ch14709] FAM- validation message cut off

src_ts/elements/common-elements/follow-up-components/follow-up-financial-findings/follow-up-financial-findings.ts
ch[14904] Audit Option not saved in Follow-Up-Financial Findings
=> ch[14904] Audit Option not saved in Follow-Up-Financial Findings

src_ts/elements/common-elements/follow-up-components/follow-up-actions/follow-up-actions.ts
=> [ch14549] Description field from Add Action Point not marked as required

src_ts/elements/common-elements/engagement-report-components/assign-engagement/assign-engagement.ts, src_ts/elements/pages/audits-page-components/report-page-components/findings-summary/fundings-summary.ts
[ch12675] Replace the “Exchange Rate” field with “Currency of Report” field
[ch12679] Summary of Audit Findings
=> [ch12675][ch12679] Replace the “Exchange Rate” field with “Currency of Report” field, Summary of Audit Findings

src_ts/elements/app-config/config.ts, src_ts/elements/app-config/endpoints.ts, src_ts/elements/core-elements/app-main-header/page-header.ts
=> [ch15376]Fix indexeddb caching

src_ts/elements/core-elements/app-main-header/page-header.ts, src_ts/elements/core-elements/app-shell-element/app-shell.ts, src_ts/elements/core-elements/app-sidebar-menu/styles/app-drawer-styles.ts
[ch15553] 'Burger' btn doesn't work
=> [ch15553] 'Burger' btn doesn't work

src_ts/elements/pages/engagements-page-components/engagements-list-view/engagements-list-view.ts
[ch15425] Add New Engagement button should not be displayed for Auditor users
=> [ch15425] Add New Engagement button should not be displayed for Auditor users

src_ts/elements/app-mixins/query-params-controller.ts, src_ts/elements/common-elements/search-and-filter-element/search-and-filter-styles.ts, src_ts/elements/common-elements/search-and-filter-element/search-and-filter.ts, src_ts/elements/pages/engagements-page-components/engagements-page-main/engagements-page-main.ts
[ch15747] FAM-Page unnecessarily reloaded on selecting new filter
=> [ch15747] Page unnecessarily reloaded on selecting new filter

src_ts/elements/pages/audits-page-components/report-page-components/findings-summary/fundings-summary.ts
[ch12679] Summary of Audit Findings. One will be in USD – mandatory and the other in local currency – non mandatory
=> [ch12679] Summary of Audit Findings

service-worker.js, sw-precache-config.js
=> [ch15784]Add Service worker config

src_ts/elements/app-mixins/common-methods-mixin.ts, src_ts/elements/app-mixins/engagement-mixin.ts, src_ts/elements/common-elements/engagement-overview-components/engagement-info-details/engagement-info-details.ts, src_ts/elements/common-elements/follow-up-components/follow-up-financial-findings/follow-up-financial-findings.ts, src_ts/elements/common-elements/follow-up-components/follow-up-main/follow-up-main.ts, src_ts/elements/pages/engagements-page-components/new-engagement-view/new-engagement-view.ts
[ch14635] FAM refactoring- engagement_type
=> [ch14635] FAM refactoring- engagement_type

index.html, src_ts/elements/app-config/config.ts, src_ts/elements/pages/micro-assessments-page-components/questionnaire-components/questionnaire-page-main/questionnaire-page-main.ts
=> [ch14261]Fix html rendered as text in Questionnaire

src_ts/elements/common-elements/engagement-report-components/specific-procedure/specific-procedure.ts
[ch16266] At saving a new Special Audit, add toast for required field 'Specific Procedure To Be Performed'
=> [ch16266] Added toast for required field 'Specific Procedure To Be Performed'

src_ts/elements/common-elements/engagement-overview-components/partner-details-tab/partner-details-tab.ts
[ch16373] PD/SSFA field in Partner Details empty after refreshing the page.
=> [ch16373] PD/SSFA field in Partner Details empty after page refresh

package-lock.json, package.json, src_ts/elements/common-elements/file-attachments-tab/file-attachments-tab.ts, src_ts/elements/data-elements/update-attachments.ts
=> [ch16443]Update the process of editing attachments

src_ts/elements/common-elements/engagement-overview-components/partner-details-tab/partner-details-tab.ts, src_ts/elements/common-elements/search-and-filter-element/search-and-filter-styles.ts, src_ts/elements/common-elements/search-and-filter-element/search-and-filter.ts, src_ts/elements/pages/engagements-page-components/engagements-list-view/engagements-list-view.ts, src_ts/elements/pages/staff-sc-page-components/staff-sc-page-main/staff-sc-page-main.ts
[ch13778] [Frontend] Create filter for year and month of engagements
=> [ch13778] Create filter for year and month of engagements

src_ts/elements/app-mixins/static-data-controller.ts, src_ts/elements/common-elements/engagement-overview-components/engagement-info-details/engagement-info-details.ts, src_ts/elements/common-elements/engagement-overview-components/partner-details-tab/partner-details-tab.ts
[ch15365] Spot Check record to capture respective Section and Office
=> [ch15365] Spot Check record to capture respective Section and Office

src_ts/elements/common-elements/engagement-overview-components/engagement-info-details/engagement-info-details.ts
=> Dev to Staging

src_ts/elements/common-elements/engagement-overview-components/engagement-info-details/engagement-info-details.ts
[ch 17465] Multiple Sections get out of engagement overview section
=> [ch 17465] Multiple Sections get out of engagement overview section

src_ts/elements/common-elements/engagement-overview-components/engagement-info-details/engagement-info-details.ts
[ch18030] FAM - miss-aligned inputs
fixed aligment issue for etools-dropdown and etools-dropdown-multi
=> [ch18030] FAM - miss-aligned inputs

src_ts/elements/pages/audits-page-components/report-page-components/findings-summary/fundings-summary.ts
=> [ch19794]Fix warning Could not find style data in module named module-styles

src_ts/elements/pages/micro-assessments-page-components/questionnaire-components/risk-tab/risk-tab.ts
=> [ch18632]Fix dropdown moving with scroll

src_ts/elements/pages/micro-assessments-page-components/questionnaire-components/risk-tab/risk-tab.ts
=> [ch18632]Fix dropdown moving along with scroll

src_ts/elements/app-config/config.ts, src_ts/elements/app-mixins/engagement-mixin.ts, src_ts/elements/app-mixins/permission-controller.ts, src_ts/elements/common-elements/engagement-overview-components/engagement-staff-members-tab/engagement-staff-members-tab.ts, src_ts/elements/common-elements/file-attachments-tab/file-attachments-tab.ts, src_ts/elements/common-elements/list-tab-elements/list-element/list-element.ts, src_ts/elements/common-elements/status-tab-element/action-buttons.ts, src_ts/elements/data-elements/update-attachments.ts, src_ts/elements/pages/audits-page-components/report-page-components/findings-summary/fundings-summary.ts
=> [ch19956]Lint fixes

src_ts/elements/common-elements/file-attachments-tab/file-attachments-tab.ts, src_ts/elements/data-elements/engagements-list-data.ts, src_ts/elements/data-elements/update-engagement.ts, src_ts/elements/pages/engagements-page-components/engagements-list-view/engagements-list-view.ts, src_ts/elements/pages/engagements-page-components/engagements-page-main/engagements-page-main.ts
[ch17673] Engagement Status not updated
=> [ch17673] Engagement Status not updated

src_ts/elements/common-elements/search-and-filter-element/search-and-filter.ts, src_ts/elements/data-elements/engagements-list-data.ts
Reverts unicef/etools-auditor-portal#379
=> Revert "[ch20753]Going back to a filtered list, after navigating to another list, shows previous applied filter, but list is not filtered"

src_ts/elements/common-elements/engagement-report-components/specific-procedure/specific-procedure.ts, src_ts/elements/pages/audits-page-components/audits-page-main/audits-page-main.ts, src_ts/elements/pages/audits-page-components/report-page-components/key-internal-controls-weaknesses/key-internal-controls-weaknesses.ts, src_ts/elements/pages/micro-assessments-page-components/micro-assessments-page-main/micro-assessments-page-main.ts, src_ts/elements/pages/special-audits-page-components/report-page-components/other-recommendations/other-recommendations.ts, src_ts/elements/pages/special-audits-page-components/special-audits-page-main/special-audits-page-main.ts, src_ts/elements/pages/spot-checks-page-components/spot-checks-page-main/spot-checks-page-main.ts, src_ts/elements/styles-elements/module-styles.ts, src_ts/elements/styles-elements/shared-styles.ts, src_ts/elements/styles-elements/tab-inputs-styles.ts
[ch20739] Cannot scroll down on dialogs
=> [ch20739] Cannot scroll down on dialogs

src_ts/elements/core-elements/app-shell-element/app-shell.ts, src_ts/elements/core-elements/app-sidebar-menu/app-menu.ts
[ch20780] Sidebar menu entry loose selection when opening record detail
=> [ch20780] Sidebar menu entry loose selection when opening record detail

.eslintrc.json, .prettierrc, package-lock.json, package.json, polymer.json, src_ts/.prettierrc
[ch20698] Setup pre-commit hooks to check linting issues
=> [ch20698] Setup pre-commit hooks to check linting issues

package-lock.json, src_ts/elements/common-elements/list-tab-elements/list-element/list-element.ts
[ch21149] Audit engagement - Report issues
=> [ch21149] Audit engagement - Report issues

src_ts/elements/common-elements/share-documents/share-documents.ts
[ch21878] Remove PMP documents from Share Documents list
=> [ch21878] Remove PMP documents from Share Documents list

express.js, package.json, polymer.json, src_ts/elements/common-elements/share-documents/share-documents.ts
* removed es5 build (#395)
* Removed source param when loading PartnerAttachments
Co-authored-by: dcioara <dan.cioara@nordlogic.com>
Co-authored-by: Dan <49279861+danNordlogic@users.noreply.github.com>
Co-authored-by: laza88 <lazaryandrei@gmail.com>
=> Staging  (#398)

src_ts/elements/pages/staff-sc-page-components/staff-sc-page-main/staff-sc-page-main.ts
[ch22402] Add filters for Staff Spot Check List
=> [ch22402] Add filters for Staff Spot Check List

src_ts/elements/common-elements/engagement-overview-components/engagement-info-details/engagement-info-details.ts, src_ts/elements/data-elements/update-agreement-data.ts
[ch24960] Contract Expiry Date not displayed after save
=> [ch24960] Contract Expiry Date not displayed after save

src_ts/elements/common-elements/file-attachments-tab/file-attachments-tab.ts
=> [ch24982]Do not show dialog spinner on file upload

src_ts/elements/common-elements/follow-up-components/follow-up-financial-findings/follow-up-financial-findings.ts, src_ts/elements/common-elements/status-tab-element/status-tab-element.ts
=> [ch24980]Make Financial Findings editable

src_ts/elements/common-elements/search-and-filter-element/search-and-filter-styles.ts, src_ts/elements/common-elements/search-and-filter-element/search-and-filter.ts
[ch24789] Add a Clear all button for Filters on both lists
=> [ch24789] Add a Clear all button for Filters on both lists

src_ts/elements/common-elements/search-and-filter-element/search-and-filter.ts
[ch25257] Standardize Clear all action: remove filters from UI and deselect selected filters from the dropdown
=> [ch25257] Standardize Clear all action: remove filters from UI and deselect selected filters from the dropdown

package-lock.json, package.json
[ch25327] Remove the unnecessary scroll showing up at save in any dialog
=> [ch25327] Remove the unnecessary scroll showing up at save in any dialog

src_ts/elements/core-elements/app-sidebar-menu/app-menu.ts, src_ts/elements/core-elements/app-sidebar-menu/styles/nav-menu-styles.ts
=> [ch25895]Show arrow to the rigth when left side menu is minimized

.circleci/config.yml, index.html, polymer.json, src_ts/elements/core-elements/app-shell-element/app-shell.ts, version.json
[ch26249]Notify the user to refresh page when a new version of the app has been deployed
=> [ch26249]Notify the user to refresh page when a new version of the app has been deployed

src_ts/elements/app-config/endpoints.ts
[ch26407] On Engagement List  an API is taking long to load
=> [ch26407] On Engagement List  an API is taking long to load

src_ts/elements/core-elements/app-shell-element/app-shell.ts
=> [ch26249]Fix refreh

src_ts/elements/common-elements/status-tab-element/status-tab-element-styles.ts
=> [ch26620]Fix status display

src_ts/elements/core-elements/app-sidebar-menu/app-menu.ts, src_ts/elements/core-elements/app-sidebar-menu/styles/nav-menu-styles.ts
=> [ch26585]Fix arrow to the right

src_ts/elements/common-elements/follow-up-components/follow-up-actions/follow-up-actions.ts, src_ts/elements/pages/spot-checks-page-components/report-page-components/summary-findings-element/summary-findings-element.ts
[ch26096] When datepicker opens, see if it can be scrolled into view
=> [ch26096] When datepicker opens, see if it can be scrolled into view

src_ts/elements/core-elements/app-main-header/page-header.ts
=> [ch26583]Refresh page after Cached data (IndexedDb) is cleared

src_ts/elements/app-shell-components/main-header/support-btn.ts
[ch26816] Update support link in header
=> [ch26816] Update support link in header

src_ts/elements/common-elements/engagement-overview-components/engagement-staff-members-tab/engagement-staff-members-tab.ts, src_ts/elements/common-elements/list-tab-elements/list-element/list-element.ts
[ch27499] Break word to next line so that the email is visible
=> [ch27499] Break word to next line so that the email is visible

src_ts/elements/app-shell-components/sidebar-menu/app-menu.ts
[ch27573] Flickering and partially displayed tooltips
=> [ch27573] Flickering and partially displayed tooltips

src_ts/elements/common-elements/engagement-overview-components/engagement-staff-members-tab/engagement-staff-members-tab.ts, src_ts/elements/common-elements/list-tab-elements/list-element/list-element.ts
[ch27642] Position and Phone Number are not displayed on Audit Staff Team Members list
=> [ch27642] Position and Phone Number are not displayed on Audit Staff Team Members list

package-lock.json, package.json, src_ts/app-shell.ts, src_ts/elements/app-shell-components/main-header/countries-dropdown/countries-dropdown.ts, src_ts/elements/app-shell-components/main-header/page-header.ts
[ch27671] Update tooltip text when hovering over app selector, Support link, user profile, refresh symbol
=> [ch27671] Update tooltip text when hovering over app selector, Support link, user profile, refresh symbol

src_ts/elements/pages/engagements/engagements-list-view/engagements-list-view.ts, src_ts/elements/pages/staff-sc/staff-sc-page-main.ts
=> [ch27547]Draft Report Issued to IP filter

.circleci/config.yml, .eslintrc.json, Dockerfile, Dockerfile-dev, package-lock.json, package.json
=> [ch27264]Update linting & formatting tools

src_ts/elements/common-elements/engagement-overview-components/engagement-staff-members-tab/engagement-staff-members-tab.ts, src_ts/elements/common-elements/list-tab-elements/list-element/list-element.ts, src_ts/elements/common-elements/list-tab-elements/list-header/list-header.ts
[ch27499][layout improvements] Break word to next line so that the email is visible
=> [ch27499][layout improvements] Break word to next line so that the email is visible

src_ts/elements/common-elements/search-and-filter-element/search-and-filter.ts, src_ts/elements/pages/engagements/engagements-list-view/engagements-list-view.ts
=> [ch27547]Label capitalization

src_ts/elements/common-elements/engagement-overview-components/engagement-staff-members-tab/engagement-staff-members-tab.ts, src_ts/elements/common-elements/list-tab-elements/list-element/list-element.ts
[ch27499][fix columns wrap] Break word to next line so that the email is visible
=> [ch27499][fix columns wrap] Break word to next line so that the email is visible

src_ts/elements/common-elements/search-and-filter-element/search-and-filter.ts
[ch27898] FAM: Filters disappear after you go back to the page
=> [ch27898] FAM: Filters disappear after you go back to the page

package-lock.json, package.json, src_ts/elements/common-elements/engagement-overview-components/engagement-info-details/engagement-info-details.ts, src_ts/elements/common-elements/engagement-report-components/assign-engagement/assign-engagement.ts, src_ts/elements/common-elements/follow-up-components/follow-up-actions/follow-up-actions.ts, src_ts/elements/mixins/common-methods-mixin.ts, src_ts/elements/pages/spot-checks/report-page-components/overview-element/overview-element.ts, src_ts/elements/pages/spot-checks/report-page-components/summary-findings-element/summary-findings-element.ts
=> [ch28146]Fixes for datepicker migration to LitElem

src_ts/elements/mixins/common-methods-mixin.ts
=> [ch28146]Fix readonly fields in Engagement Status

src_ts/elements/pages/spot-checks/report-page-components/overview-element/overview-element.ts
[ch28151] Date fields revert to previous value after Save
=> [ch28151] Date fields revert to previous value after Save

src_ts/elements/common-elements/engagement-overview-components/engagement-staff-members-tab/engagement-staff-members-tab.ts, src_ts/elements/common-elements/engagement-report-components/specific-procedure/specific-procedure.ts, src_ts/elements/common-elements/file-attachments-tab/file-attachments-tab.ts, src_ts/elements/common-elements/follow-up-components/follow-up-actions/follow-up-actions.ts, src_ts/elements/mixins/common-methods-mixin.ts, src_ts/elements/pages/audits/audits-page-main.ts, src_ts/elements/pages/audits/report-page-components/assessment-of-controls/assessment-of-controls.ts, src_ts/elements/pages/audits/report-page-components/financial-findings/financial-findings.ts, src_ts/elements/pages/audits/report-page-components/findings-summary/fundings-summary.ts, src_ts/elements/pages/audits/report-page-components/key-internal-controls-weaknesses/key-internal-controls-weaknesses.ts, src_ts/elements/pages/micro-assessments/micro-assessments-page-main.ts, src_ts/elements/pages/micro-assessments/questionnaire-components/questionnaire-page-main/questionnaire-page-main.ts, src_ts/elements/pages/micro-assessments/report-page-components/control-findings-tab.ts, src_ts/elements/pages/micro-assessments/report-page-components/key-internal-controls-tab.ts, src_ts/elements/pages/special-audits/report-page-components/other-recommendations/other-recommendations.ts, src_ts/elements/pages/special-audits/special-audits-page-main.ts, src_ts/elements/pages/spot-checks/report-page-components/summary-findings-element/summary-findings-element.ts, src_ts/elements/pages/spot-checks/spot-checks-page-main.ts
[ch28197] If you cancel on a dialog, the dialog will not open again
=> [ch28197] If you cancel on a dialog, the dialog will not open again

src_ts/elements/common-elements/engagement-overview-components/engagement-info-details/engagement-info-details.ts, src_ts/elements/data-elements/get-agreement-data.ts, src_ts/elements/data-elements/update-agreement-data.ts, src_ts/elements/utils/utils.ts, src_ts/types/global.ts
=> [ch28340] Remove double bindings from engagement details

package-lock.json, package.json, src_ts/elements/common-elements/engagement-report-components/specific-procedure/specific-procedure.ts
[ch28625] Handle security issues on repos
=> [ch28625] Handle security issues on repos

src_ts/app-shell.ts, src_ts/elements/common-elements/search-and-filter-element/search-and-filter.ts, src_ts/elements/mixins/engagement-mixin.ts
=> [ch28601] [ch28465] Filters clear

src_ts/elements/common-elements/search-and-filter-element/search-and-filter.ts
=> [ch28602] Fix search clear after page reload

src_ts/elements/common-elements/engagement-overview-components/engagement-info-details/engagement-info-details.ts, src_ts/elements/common-elements/engagement-overview-components/partner-details-tab/partner-details-tab.ts, src_ts/elements/data-elements/get-partner-data.ts, src_ts/elements/mixins/common-methods-mixin.ts
=> [ch28605] Remove double bindings from partner-details

src_ts/elements/common-elements/file-attachments-tab/file-attachments-tab-styles.ts, src_ts/elements/common-elements/file-attachments-tab/file-attachments-tab.ts
=> [ch28724]Fix broken link

src_ts/elements/common-elements/engagement-report-components/specific-procedure/specific-procedure.ts, src_ts/elements/pages/audits/report-page-components/key-internal-controls-weaknesses/key-internal-controls-weaknesses.ts, src_ts/elements/pages/spot-checks/report-page-components/summary-findings-element/summary-findings-element.ts
[ch28618] Missing validation error
=> [ch28618] Missing validation error

src_ts/elements/pages/micro-assessments/questionnaire-components/questionnaire-page-main/questionnaire-page-main.ts, src_ts/elements/pages/micro-assessments/questionnaire-components/risk-tab/risk-tab.ts
=> [ch28379] Prevent starting new risk request when another one is active

.circleci/config.yml, src_ts/elements/common-elements/engagement-overview-components/engagement-info-details/engagement-info-details.ts, src_ts/elements/styles/tab-inputs-styles.ts
=> [ch28458]Fix "Notified When Completed" for auditor user

src_ts/elements/pages/micro-assessments/questionnaire-components/questionnaire-page-main/questionnaire-page-main.ts
=> [ch28871] Fix loading of MA pages

src_ts/elements/common-elements/list-tab-elements/list-tab-main/list-tab-main.ts
=> [ch28878] [ch28897] Fix list pagination

src_ts/elements/common-elements/pages-header-element/pages-header-element.ts, src_ts/elements/pages/engagements/engagements-list-view/engagements-list-view.ts, src_ts/elements/pages/engagements/engagements-page-main.ts, src_ts/elements/pages/staff-sc/staff-sc-page-main.ts
=> [ch29095] Id to reference

src_ts/elements/app-shell-components/sidebar-menu/app-menu.ts
=> [ch29414]Update Implementation Intelligence link

src_ts/elements/common-elements/engagement-overview-components/engagement-info-details/engagement-info-details.ts
=> [ch30231] Fix PO error

.circleci/config.yml, src_ts/elements/common-elements/engagement-overview-components/partner-details-tab/partner-details-tab.ts
=> [ch30577]Cannot create engagement: required Partner validation

src_ts/elements/common-elements/engagement-overview-components/engagement-staff-members-tab/engagement-staff-members-tab.ts
=> [ch30582]Fix staff members issues

src_ts/app-shell.ts
[ch30569] [Action Points]Replace the use of this.$
=> [ch30569] [Action Points]Replace the use of this.$

src_ts/elements/common-elements/engagement-overview-components/engagement-info-details/engagement-info-details.ts
[ch30599] Engagement Overview: Joint Audit option not saved
=> [ch30599] Engagement Overview: Joint Audit option not saved

src_ts/elements/common-elements/engagement-overview-components/engagement-staff-members-tab/engagement-staff-members-tab.ts
=> [ch30643]Fix validation inconsistency

src_ts/elements/common-elements/follow-up-components/follow-up-actions/follow-up-actions.ts
=> [ch30820]Fix reopen action point after duplicating

src_ts/elements/common-elements/follow-up-components/follow-up-actions/follow-up-actions.ts
=> [ch30827]Add Copy AP tooltip

src_ts/elements/mixins/engagement-mixin.ts
=> [ch32032]Do not redirect to follow-up page for auditor

package-lock.json, package.json, src_ts/app-shell.ts, src_ts/elements/common-elements/status-tab-element/action-buttons.ts, src_ts/elements/mixins/engagement-mixin.ts, src_ts/elements/pages/engagements/engagements-page-main.ts, src_ts/elements/pages/staff-sc/staff-sc-page-main.ts
=> [ch32526]All toasts to have ok btn

src_ts/elements/app-shell-components/main-header/header-elements/countries-dropdown.ts, src_ts/elements/app-shell-components/main-header/header-elements/organizations-dropdown.ts, src_ts/elements/common-elements/engagement-overview-components/engagement-staff-members-tab/engagement-staff-members-tab.ts, src_ts/elements/common-elements/list-tab-elements/list-element/list-element.ts
[ch33671] AMP: changes and performance improvements
=> [ch33671] AMP: changes and performance improvements

src_ts/elements/common-elements/engagement-overview-components/engagement-info-details/engagement-info-details.ts, src_ts/elements/common-elements/pages-header-element/pages-header-element.ts, src_ts/elements/pages/engagements/new-engagement-view/new-engagement-view.ts
=> [ch33760] 'Shared with' Dropdown error on first value select

src_ts/elements/common-elements/engagement-overview-components/engagement-staff-members-tab/engagement-staff-members-tab.ts
=> [ch33573]Single dropdown has an offset on certain pages

src_ts/elements/common-elements/engagement-overview-components/engagement-info-details/engagement-info-details.ts
=> [ch33837]Use actual year instead of > 1 year ago

src_ts/elements/config/endpoints.ts
[ch33921] Replace `v2/partners` endpoints with `pmp/v3/partners`
=> [ch33921] Replace `v2/partners` endpoints with `pmp/v3/partners`

src_ts/elements/common-elements/engagement-overview-components/engagement-staff-members-tab/engagement-staff-members-tab.ts
[ch33961] All staff members are shown as inactive
=> [ch33961] All staff members are shown as inactive

src_ts/elements/data-elements/update-attachments.ts
=> [ch33973]Fix delete attachment

src_ts/elements/common-elements/follow-up-components/follow-up-actions/follow-up-actions.ts
=> [ch33910]Related Partner/PD not displayed in the Action point dialog

package-lock.json, package.json
[ch33867] Users cannot access the module when using Firefox or Edge
=> [ch33867] Users cannot access the module when using Firefox or Edge

src_ts/elements/common-elements/engagement-report-components/assign-engagement/assign-engagement.ts, src_ts/elements/utils/utils.ts
[ch33912] Add a toast for Currency of Report required
=> [ch33912] Add a toast for Currency of Report required

src_ts/elements/common-elements/list-tab-elements/list-tab-main/list-tab-main.ts, src_ts/elements/data-elements/engagements-list-data.ts
[ch34068] Display just the toast for organization selection
=> [ch34068] Display just the toast for organization selection

src_ts/elements/mixins/common-methods-mixin.ts
=> [ch34062]Ensure users_notified are shown

src_ts/elements/common-elements/engagement-overview-components/engagement-staff-members-tab/engagement-staff-members-tab.ts, src_ts/elements/common-elements/list-tab-elements/list-element/list-element.ts, src_ts/elements/data-elements/get-partner-data.ts
=> [ch34085]Firm members list -  Inactive and No Access

src_ts/app-shell.ts
[ch34156] Background blur of the dialog disappears after selecting a value in the dropdown
=> [ch34156] Background blur of the dialog disappears after selecting a value in the dropdown

src_ts/elements/pages/micro-assessments/questionnaire-components/questionnaire-page-main/questionnaire-page-main.ts
=> [ch33736]Fix dropdown cut off

.circleci/config.yml, src_ts/elements/pages/micro-assessments/micro-assessments-page-main.ts, src_ts/elements/pages/micro-assessments/questionnaire-components/questionnaire-page-main/questionnaire-page-main.ts
[ch33736] FAM: Change Micro Assessment Questionnaire
=> [ch33736] FAM: Change Micro Assessment Questionnaire

src_ts/elements/common-elements/engagement-overview-components/engagement-info-details/engagement-info-details.ts, src_ts/elements/common-elements/engagement-overview-components/partner-details-tab/partner-details-tab.ts, src_ts/elements/common-elements/engagement-report-components/specific-procedure/specific-procedure.ts, src_ts/elements/common-elements/file-attachments-tab/file-attachments-tab.ts, src_ts/elements/common-elements/follow-up-components/follow-up-main/follow-up-main.ts, src_ts/elements/common-elements/status-tab-element/action-buttons.ts, src_ts/elements/mixins/engagement-mixin.ts, src_ts/elements/mixins/table-elements-mixin.ts, src_ts/elements/pages/audits/audits-page-main.ts, src_ts/elements/pages/audits/report-page-components/assessment-of-controls/assessment-of-controls.ts, src_ts/elements/pages/audits/report-page-components/financial-findings/financial-findings.ts, src_ts/elements/pages/audits/report-page-components/key-internal-controls-weaknesses/key-internal-controls-weaknesses.ts, src_ts/elements/pages/engagements/new-engagement-view/new-engagement-view.ts, src_ts/elements/pages/micro-assessments/micro-assessments-page-main.ts, src_ts/elements/pages/micro-assessments/questionnaire-components/questionnaire-page-main/questionnaire-page-main.ts, src_ts/elements/pages/micro-assessments/report-page-components/control-findings-tab.ts, src_ts/elements/pages/micro-assessments/report-page-components/key-internal-controls-tab.ts, src_ts/elements/pages/special-audits/report-page-components/other-recommendations/other-recommendations.ts, src_ts/elements/pages/special-audits/special-audits-page-main.ts, src_ts/elements/pages/spot-checks/report-page-components/summary-findings-element/summary-findings-element.ts, src_ts/elements/pages/spot-checks/spot-checks-page-main.ts
[ch35022] FAM Lit migration other issues
=> [ch35022] FAM Lit migration other issues

src_ts/elements/common-elements/engagement-overview-components/engagement-info-details/engagement-info-details.ts, src_ts/elements/common-elements/follow-up-components/follow-up-actions/follow-up-actions.ts, src_ts/elements/common-elements/follow-up-components/follow-up-main/follow-up-main.ts, src_ts/elements/mixins/permission-controller.ts, src_ts/elements/pages/engagements/new-engagement-view/new-engagement-view.ts
[ch35045] FAM Lit migration other issues 3
=> [ch35045] FAM Lit migration other issues 3

src_ts/elements/common-elements/file-attachments-tab/file-attachments-tab.ts, src_ts/elements/common-elements/share-documents/share-documents.ts, src_ts/elements/pages/micro-assessments/report-page-components/ma-report-page-main.ts, src_ts/elements/pages/micro-assessments/report-page-components/subject-area-element.ts
[ch35066] FAM Lit migration other issues 4
=> [ch35066] FAM Lit migration other issues 4

src_ts/elements/common-elements/follow-up-components/follow-up-actions/follow-up-actions.ts, src_ts/elements/common-elements/follow-up-components/follow-up-financial-findings/follow-up-financial-findings.ts, src_ts/elements/mixins/engagement-mixin.ts, src_ts/elements/pages/engagements/engagements-page-main.ts, src_ts/elements/pages/micro-assessments/questionnaire-components/questionnaire-page-main/questionnaire-page-main.ts, src_ts/elements/styles/module-styles.ts
[ch35116] FAM Lit migration issues 5
=> [ch35116] FAM Lit migration issues 5

src_ts/elements/common-elements/file-attachments-tab/file-attachments-tab.ts, src_ts/elements/common-elements/pages-header-element/pages-header-element.ts, src_ts/elements/pages/spot-checks/report-page-components/sc-report-page-main/sc-report-page-main.ts, src_ts/elements/pages/spot-checks/report-page-components/summary-findings-element/summary-findings-element.ts
[ch35176] FAM Lit migration issues 6
=> [ch35176] FAM Lit migration issues 6

src_ts/app-shell.ts, src_ts/elements/common-elements/engagement-overview-components/engagement-info-details/engagement-info-details.ts, src_ts/elements/common-elements/engagement-overview-components/engagement-staff-members-tab/engagement-staff-members-tab.ts, src_ts/elements/pages/engagements/new-engagement-view/new-engagement-view.ts, src_ts/elements/pages/micro-assessments/report-page-components/key-internal-controls-tab.ts, src_ts/elements/pages/special-audits/special-audits-page-main.ts, src_ts/elements/styles/main-page-styles.ts, src_ts/elements/styles/module-styles.ts, src_ts/redux/actions/common-data.ts, src_ts/redux/reducers/common-data.ts, src_ts/redux/reducers/engagement.ts
[ch35656] FAM Lit Migration issues 7
=> [ch35656] FAM Lit Migration issues 7

src_ts/elements/common-elements/engagement-overview-components/partner-details-tab/partner-details-tab.ts, src_ts/redux/actions/app.ts
[ch35701] FAM replace components with Shoelace components (Refactor dynamic imports)
=> [ch35701] FAM replace components with Shoelace components (Refactor dynamic imports)

assets/css/app-theme.css, package-lock.json, package.json, src_ts/app-shell.ts, src_ts/elements/common-elements/engagement-overview-components/engagement-info-details/engagement-info-details.ts, src_ts/elements/common-elements/engagement-overview-components/engagement-staff-members-tab/engagement-staff-members-tab.ts, src_ts/elements/common-elements/engagement-report-components/specific-procedure/specific-procedure.ts, src_ts/elements/common-elements/file-attachments-tab/file-attachments-tab.ts, src_ts/elements/common-elements/pages-header-element/pages-header-element.ts, src_ts/elements/common-elements/share-documents/share-documents.ts, src_ts/elements/mixins/common-methods-mixin.ts, src_ts/elements/mixins/table-elements-mixin.ts, src_ts/elements/pages/audits/audits-page-main.ts, src_ts/elements/pages/audits/report-page-components/assessment-of-controls/assessment-of-controls.ts, src_ts/elements/pages/audits/report-page-components/financial-findings/financial-findings.ts, src_ts/elements/pages/audits/report-page-components/findings-summary/findings-summary.ts, src_ts/elements/pages/audits/report-page-components/key-internal-controls-weaknesses/key-internal-controls-weaknesses.ts, src_ts/elements/pages/audits/report-page-components/kicw-risk/kicw-risk.ts, src_ts/elements/pages/micro-assessments/micro-assessments-page-main.ts, src_ts/elements/pages/micro-assessments/questionnaire-components/risk-tab/risk-tab.ts, src_ts/elements/pages/micro-assessments/report-page-components/control-findings-tab.ts, src_ts/elements/pages/micro-assessments/report-page-components/key-internal-controls-tab.ts, src_ts/elements/pages/micro-assessments/report-page-components/subject-area-element.ts, src_ts/elements/pages/special-audits/report-page-components/other-recommendations/other-recommendations.ts, src_ts/elements/pages/special-audits/special-audits-page-main.ts, src_ts/elements/pages/spot-checks/report-page-components/summary-findings-element/summary-findings-element.ts, src_ts/elements/pages/spot-checks/spot-checks-page-main.ts, src_ts/elements/styles/module-styles.ts, src_ts/elements/utils/utils.ts, src_ts/redux/reducers/common-data.ts
[ch35804] FAM Fixes after Shoelace migration
=> [ch35804] FAM Fixes after Shoelace migration

assets/css/app-theme.css, package-lock.json, package.json, src_ts/app-shell.ts, src_ts/elements/app-shell-components/sidebar-menu/app-menu.ts, src_ts/elements/app-shell-components/sidebar-menu/mixins/app-menu-mixin.ts, src_ts/elements/app-shell-components/sidebar-menu/styles/nav-menu-styles.ts, src_ts/elements/common-elements/engagement-overview-components/engagement-info-details/engagement-info-details.ts, src_ts/elements/common-elements/engagement-overview-components/engagement-staff-members-tab/engagement-staff-members-tab.ts, src_ts/elements/common-elements/engagement-overview-components/partner-details-tab/partner-details-tab.ts, src_ts/elements/common-elements/engagement-report-components/assign-engagement/assign-engagement.ts, src_ts/elements/common-elements/file-attachments-tab/file-attachment-doc-dialog.ts, src_ts/elements/common-elements/follow-up-components/follow-up-actions/follop-up-actions-dialog.ts, src_ts/elements/common-elements/follow-up-components/follow-up-actions/follow-up-actions.ts, src_ts/elements/common-elements/status-tab-element/action-buttons.ts, src_ts/elements/config/config.ts, src_ts/elements/mixins/engagement-mixin.ts, src_ts/elements/pages/audits/audits-page-main.ts, src_ts/elements/pages/engagements/engagements-list-view/engagements-list-view.ts, src_ts/elements/pages/engagements/engagements-list-view/staff-sc-list-view.ts, src_ts/elements/pages/engagements/new-engagement-view/new-engagement-view.ts, src_ts/elements/styles/module-styles.ts
[ch35892] FAM Shoelace Migration Issues
=> [ch35892] FAM Shoelace Migration Issues

package-lock.json, package.json, src_ts/elements/app-shell-components/sidebar-menu/styles/app-drawer-styles.ts, src_ts/elements/common-elements/engagement-overview-components/engagement-info-details/engagement-info-details.ts, src_ts/elements/common-elements/engagement-overview-components/engagement-staff-members-tab/engagement-staff-members-tab.ts, src_ts/elements/mixins/common-methods-mixin.ts, src_ts/elements/pages/audits/audits-page-main.ts, src_ts/elements/pages/audits/report-page-components/findings-summary/findings-summary-dialog.ts, src_ts/elements/pages/micro-assessments/micro-assessments-page-main.ts, src_ts/elements/pages/special-audits/special-audits-page-main.ts, src_ts/elements/pages/spot-checks/spot-checks-page-main.ts
[ch35912] FAM Shoelace Migration Issues 2
=> [ch35912] FAM Shoelace Migration Issues 2

src_ts/elements/common-elements/engagement-overview-components/engagement-info-details/engagement-info-details.ts, src_ts/elements/common-elements/status-tab-element/status-tab-element.ts
[ch35947] FAM Shoelace Migration Issues 3
=> [ch35947] FAM Shoelace Migration Issues 3

src_ts/elements/common-elements/engagement-overview-components/engagement-staff-members-tab/engagement-staff-members-tab.ts
[ch35950] Hide link to AMP if Engagement doesn't have Auditor firm
=> [ch35950] Hide link to AMP if Engagement doesn't have Auditor firm

package-lock.json, package.json, src_ts/elements/common-elements/engagement-overview-components/engagement-info-details/engagement-info-details.ts, src_ts/elements/utils/utils.ts
[ch35947] FAM Shoelace Migration Issues 3
=>  [ch35947] FAM Shoelace Migration Issues 3

assets/images/flag-icon.svg, src_ts/elements/common-elements/engagement-cancel/engagement-cancel-dialog.ts, src_ts/elements/common-elements/engagement-report-components/send-back-comment/send-back-comment.ts, src_ts/elements/common-elements/status-tab-element/action-buttons-styles.ts, src_ts/elements/common-elements/status-tab-element/action-buttons.ts, src_ts/elements/data-elements/update-engagement.ts, src_ts/elements/mixins/engagement-mixin.ts, src_ts/elements/pages/audits/audits-page-main.ts, src_ts/elements/pages/audits/report-page-components/audit-report-page-main/audit-report-page-main.ts, src_ts/elements/pages/micro-assessments/micro-assessments-page-main.ts, src_ts/elements/pages/micro-assessments/report-page-components/ma-report-page-main.ts, src_ts/elements/pages/special-audits/report-page-components/sa-report-page-main/sa-report-page-main.ts, src_ts/elements/pages/special-audits/special-audits-page-main.ts, src_ts/elements/pages/spot-checks/report-page-components/sc-report-page-main/sc-report-page-main.ts, src_ts/elements/pages/spot-checks/spot-checks-page-main.ts
[ch35977] FAM engagements: Add a send back option
=> [ch35977] FAM engagements: Add a send back option

package-lock.json, package.json, src_ts/elements/common-elements/engagement-overview-components/engagement-staff-members-tab/engagement-staff-members-tab.ts, src_ts/elements/common-elements/follow-up-components/follow-up-actions/follop-up-actions-dialog.ts, src_ts/elements/common-elements/follow-up-components/follow-up-actions/follow-up-actions.ts, src_ts/elements/pages/audits/report-page-components/assessment-of-controls/assessment-of-controls.ts, src_ts/elements/pages/micro-assessments/report-page-components/primary-risk-element.ts, src_ts/elements/styles/module-styles.ts, src_ts/elements/styles/tab-inputs-styles.ts
[ch36299] FAM Shoelace Migration Issues 4
=> [ch36299] FAM Shoelace Migration Issues 4

src_ts/elements/common-elements/file-attachments-tab/file-attachments-tab-styles.ts, src_ts/elements/common-elements/file-attachments-tab/file-attachments-tab.ts, src_ts/elements/common-elements/file-attachments-tab/share-documents-dialog.ts, src_ts/elements/common-elements/follow-up-components/follow-up-financial-findings/follow-up-financial-findings.ts, src_ts/elements/data-elements/update-engagement.ts, src_ts/elements/mixins/common-methods-mixin.ts, src_ts/elements/mixins/table-elements-mixin.ts, src_ts/elements/pages/audits/report-page-components/financial-findings/financial-findings.ts, src_ts/elements/pages/audits/report-page-components/findings-summary/findings-summary.ts, src_ts/elements/pages/audits/report-page-components/key-internal-controls-weaknesses/key-internal-controls-weaknesses.ts, src_ts/elements/pages/micro-assessments/report-page-components/key-internal-controls-tab.ts, src_ts/elements/pages/micro-assessments/report-page-components/primary-risk-element.ts, src_ts/elements/pages/spot-checks/report-page-components/summary-findings-element/summary-findings-element.ts
=> FAM migration tweaks

package-lock.json, package.json
=> Fix dropdown width

src_ts/elements/data-elements/update-engagement.ts, src_ts/elements/utils/utils.ts
=> Fix toasts messages

src_ts/elements/data-elements/get-staff-members-list.ts, src_ts/elements/pages/engagements/engagements-list-view/list-view-base.ts, src_ts/elements/pages/staff-sc/staff-sc-page-main.ts
=> [ch36680] error aborted

src_ts/elements/common-elements/follow-up-components/follow-up-actions/follop-up-actions-dialog.ts, src_ts/elements/common-elements/follow-up-components/follow-up-actions/follow-up-actions.ts, src_ts/elements/pages/spot-checks/report-page-components/summary-findings-element/summary-findings-dialog.ts, src_ts/elements/pages/spot-checks/report-page-components/summary-findings-element/summary-findings-element.ts
=> Fix for datepicker in popup

src_ts/elements/common-elements/follow-up-components/follow-up-actions/follop-up-actions-dialog.ts
[ch36053]  Limiting the excessive usage of "other" as a category type for Action points.
=> [ch36053]  Limiting the excessive usage of "other" as a category type for Action points.

package-lock.json, package.json, src_ts/elements/common-elements/follow-up-components/follow-up-actions/follow-up-actions.ts
[ch37420] in FAM module 'duplicate button' is displayed over the priority status
=> [ch37420] in FAM module 'duplicate button' is displayed over the priority status

package-lock.json, package.json, src_ts/elements/common-elements/engagement-overview-components/engagement-staff-members-tab/engagement-staff-members-tab.ts
[ch39554] Move `pagination-mixin` to `etools-unicef/etools-data-table`,  it is used only by this component, update apps
=> [ch39554] Move `pagination-mixin` to `etools-unicef/etools-data-table`,  it is used only by this component, update apps
